"""Update contract migration

Revision ID: 76cb8f855b59
Revises: c33731fe191e
Create Date: 2024-06-22 23:10:45.715638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cb8f855b59'
down_revision: Union[str, None] = 'c33731fe191e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_addresses_city', table_name='addresses')
    op.drop_index('ix_addresses_country', table_name='addresses')
    op.drop_index('ix_addresses_id', table_name='addresses')
    op.drop_index('ix_addresses_postal_code', table_name='addresses')
    op.drop_index('ix_addresses_state', table_name='addresses')
    op.drop_index('ix_addresses_street', table_name='addresses')
    op.drop_table('addresses')
    op.add_column('contracts', sa.Column('dimensional_factor', sa.Float(), nullable=True))
    op.drop_column('postal_code_ranges', 'delivery_rate_per_volume')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postal_code_ranges', sa.Column('delivery_rate_per_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('contracts', 'dimensional_factor')
    op.create_table('addresses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='addresses_pkey')
    )
    op.create_index('ix_addresses_street', 'addresses', ['street'], unique=False)
    op.create_index('ix_addresses_state', 'addresses', ['state'], unique=False)
    op.create_index('ix_addresses_postal_code', 'addresses', ['postal_code'], unique=False)
    op.create_index('ix_addresses_id', 'addresses', ['id'], unique=False)
    op.create_index('ix_addresses_country', 'addresses', ['country'], unique=False)
    op.create_index('ix_addresses_city', 'addresses', ['city'], unique=False)
    # ### end Alembic commands ###
